# Generated by Django 5.2.12 on 2026-03-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_insuranceplan_billing_frequency_alter_claim_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes from admin', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for claim rejection', null=True),
        ),
    ]
